.gitignore
config.toml
layouts/_default/post.html
layouts/_default/project.html
layouts/_default/service.html
layouts/partials/footer.html
layouts/partials/header.html
layouts/partials/sidebar.html
layouts/service/single.html

- Replace absURL with relURL
- Fix social links

Fix absURL

---

config.toml
data/en/homepage.yml
data/zh/homepage.yml

- Remove several modules of the theme
- Update descriptions in config file

Update themes modules

---

data/en/homepage.yml

Update en homepage.

---

assets/scss/_common.scss
content/en/team/dongyitao.md
content/en/team/longheng.md
content/en/team/nipengfei.md
content/en/team/suwei.md
content/en/team/zhangliying.md

fix css and add English profile for steering committes

---

config.toml
content/en/blog/cnc-announcement.md
data/en/homepage.yml

Update community intro

---

content/en/team/suwei.md
content/en/team/zhangliying.md
content/zh/team/suwei.md
content/zh/team/zhangliying.md

update team profile

---

content/en/team/suwei.md
content/zh/team/suwei.md

update suwei's profile

---

content/en/team/suwei.md
content/zh/team/suwei.md

> 请保留以下声明。 
更新Su Wei profile link.

更新Su Wei profile link.

---

assets/scss/templates/_blog.scss

Add `max-width` for blog image

---

assets/scss/_typography.scss
content/en/blog/cnc-announcement.md

update text transform

---

content/zh/blog/how-tekton-works/index.md

new post: Tekton 的工作原理

---

i18n/en.yaml
i18n/zh.yaml
layouts/_default/post.html
layouts/_default/single.html

Add translator parameter for blog post

---

content/zh/blog/oam-crossplane/index.md

post: oam and plane: The Next Stage for Building Modern Application

---

content/zh/blog/istio-certificate/index.md

Signed-off-by: Huabing Zhao <zhaohuabing@gmail.com>
> 请保留以下声明。 

istio certificated explained

---

README.md

**Why need this PR:**
增加项目技术栈介绍和启动介绍，方便开发快速入手

add dev guide

---

README.md

修复readme markdown 语法错误

---

assets/scss/templates/_navigation.scss
layouts/partials/footer.html
layouts/partials/head.html
layouts/partials/header.html

Add Algolia DocSearch (#77)

---

config.toml
layouts/_default/single.html

add comment

---

assets/scss/style.scss
assets/scss/templates/_sidebar.scss
assets/scss/templates/_slider.scss
i18n/en.yaml
i18n/fr.yaml
i18n/zh.yaml
layouts/_default/single.html
layouts/partials/related.html
layouts/partials/sidebar.html

New layout

---

assets/scss/templates/_navigation.scss

Fix search style (#77)

---

config.toml
content/en/blog/cnc-announcement.md
content/en/contact/_index.md
data/en/about.yml
data/en/homepage.yml

> 请保留以下声明。 
^ agreed
Correct some English, in particular "有温度的" should not be translated as "with a temperature" as in English this means you are ill with a fever.

A few fixes to the English content

---

content/zh/blog/cloud-native-mosn/index.md

[blog] 云原生网络代理 MOSN 的进化之路

---

content/zh/job/trip-cloud-native.md

* Create trip-cloud-native.md
> 请保留以下声明。

   [job] 携程 container&service team

---

content/zh/job/ebay-cloud-native.md

[job] ebay cloud native招聘

---

content/zh/job/api7.md

[job][update] 深圳支流科技有限公司 

---

assets/scss/templates/_blog.scss
i18n/en.yaml
i18n/fr.yaml
i18n/zh.yaml
layouts/_default/single.html
layouts/partials/previous.html

feature: add link article

---

content/zh/blog/kubernetes-programming-base/index.md

fix spelling error

---

content/zh/blog/informer-study/index.md

fix typo error

---

content/zh/blog/informer-study/index.md

fix type error and ordered list not display error

---

content/en/team/lihui.md
content/zh/team/lihui.md

合伙人 厉辉 个人介绍有问题，修复该问题
> 请保留以下声明。

修复合伙人介绍中存在的 typo

---

content/zh/blog/istio-pilot-2/index.md
content/zh/blog/istio-pilot-3/index.md

> 请保留以下声明。
- 修改部分拼写错误
- 去除部分不太重要的单词高亮，突出重点
- 图片添加说明，便于公众号显示
@rootsongjc PTAL

adjust the code highlights && fix typo

---

assets/scss/templates/_city.scss

increase city page box-div to 500px

---

content/zh/job/chinatelecom-k8s.md

[招聘]中国电信股份有限公司云计算分公司容器组

---

content/zh/blog/envoy-trans-recruit/index.md

[blog] 添加 Envoy 志愿者招募信息

---

content/zh/blog/must-read-for-cloud-native-beginner/index.md

[Review] format, punctuation, characters。

---

assets/js/city.js
layouts/_default/city.html

添加城市选中之后的Highlight

---

content/zh/city/wuhan.md

Signed-off-by: shaowenchen <mail@chenshaowen.com>
> 请保留以下声明。

bugfix: fix error link for wuhan site

---

content/zh/city/nanjing.md

修复南京站经纬度数据，以解决在地图上无法显示的问题

---

content/zh/job/aliyun-sls-observability.md

add 阿里云SLS可观察性方向招聘信息

---

content/zh/blog/envoy-http-connection-management/index.md

[翻译] envoy HTTP connection management.

---

config.toml
layouts/partials/footer.html

Use variable-year in copyrights.

---

content/zh/job/geely-cloud-native copy.md

[job] 吉利汽车

---

content/zh/blog/service-mesh-comparison-istio-vs-linkerd/index.md

#327 tanslate Service Mesh Comparison: Istio vs Linkerd

---

content/zh/job/tal-cloud-native.md

add 好未来基础服务中台服务网格招聘信息

---

content/zh/job/alibaba-cloud-eci.md

[job] 阿里云容器研发方向招聘信息

---

content/zh/job/weixin-k8s.md

[job] 微信技术架构部大数据系统开发工程师

---

content/zh/job/youzan-cloud-native.md

Feat update date

---

content/zh/job/youzan-cloud-native.md

Fix datetime

---

content/zh/job/tencent-tke.md

[job]腾讯云容器产品中心招聘容器高级开发工程师

---

content/zh/job/vesoft-cloud-native.md

[job] 欧若数网-云产品团队Golang开发工程师招聘信息

---

content/zh/job/dewu/index.md

Signed-off-by: Herman Zhu <zhuhuijunzhj@gmail.com>
> 请保留以下声明。

add dewu job

---

content/zh/blog/edgeadm-kubernetes/index.md

edgeadm kubernetes add bilibili video link
> 请保留以下声明。

edgeadm kubernetes add bilibili video link

---

content/zh/job/moore-threads-dev-infra/index.md

add some jobs decs from mthreads dev infra team.
> 请保留以下声明。

摩尔线程Dev&Infra部门招聘DevOps和Backend Engineer

---

content/en/team/guoxudong.md
content/zh/city/shanghai.md
content/zh/team/guoxudong.md

update info of guoxuodng

---

content/zh/blog/scaling-kubernetes-with-assurance-at-pinterest/index.md

translate: scaling kubernetes with assurance at pinterest

---

content/en/team/luoguangming.md
content/zh/team/luoguangming.md

update luoguangming's profile

---

content/zh/job/trip-service-mesh/index.md

[job] ctrip mesh

---

content/zh/city/guangzhou.md
content/zh/team/zhangxh.md

update self introduction

---

content/zh/blog/image-trusted-repository-with-open-policy-agent/index.md

文章：使用 Open Policy Agent 实现可信镜像仓库检查

---

content/zh/team/majinghe.md

modify company info

---

content/zh/blog/image-trusted-repository-with-open-policy-agent/index.md
content/zh/city/guangzhou.md
content/zh/team/zhangxh.md

update company info

---

content/zh/job/horizon/index.md

Signed-off-by: Herman Zhu <zhuhuijunzhj@gmail.com>
> 请保留以下声明。

job(horizon) update jd date

---

content/en/team/zhangxh.md

upload xiaohui' english personal page

---

content/zh/city/beijing.md

Update guangming's profie

---

content/blog/gitops-flux/index.md

improve: 将截图修改为文字

---

content/home/slider.md

> 请保留以下声明。
我已阅读[投稿指南](https://cloudnative.to/community/contribute/)和[风格指南](https://cloudnative.to/community/contribute/style/)，并授权[云原生社区](https://cloudnative.to)发布我原创或翻译的文章，我将保留对本文署名的权利。w
修改了 IOSF 举办的信息，由于深圳疫情原因，原定于 9 月 15 -17 日举办的活动已经推迟举行，时间未定。

modify IOSF delay info

---

content/blog/retrospect-service-mesh-summit/index.md

> 请保留以下声明。
我已阅读[投稿指南](https://cloudnative.to/community/contribute/)和[风格指南](https://cloudnative.to/community/contribute/style/)，并授权[云原生社区](https://cloudnative.to)发布我原创或翻译的文章，我将保留对本文署名的权利。w

add new post: retrospect of service mesh summit

---

content/authors/宋建昌/_index.md
content/authors/李倩/_index.md
content/authors/陈晨/_index.md

> 请保留以下声明。
Fix some errors about author infos.

Fix author infos

---

content/blog/service_map_observation_performance_test/index.md

[投稿]使用全景拓扑持续跟踪云原生应用的压测性能瓶颈

---

content/authors/林静/_index.md
content/blog/kubernetes-secure-development-best-practices-in-action/index.md
content/blog/why-we-decided-to-start-fresh-with-our-nginx-gateway-fabric/index.md
content/translators/林静/_index.md

【投稿】2篇译文，一篇关于NGINX Gateway Fabric项目，一篇关于基于k8s的安全开发实践

---

content/blog/prometheus-operator-manual/index.md

chore(typo):  fix update blog/prometheus-operator-manual/index.md

---

content/blog/jd-grandshorestech/index.md

Update index.md 更新JD
